image: maven

stages:
  - analyze

sonar_analysis:
  stage: analyze
  script:
      mvn -B -ntp sonar:sonar \
        -Dsonar.host.url=http://coursework.cs.duke.edu:9000 \
        -Dsonar.sources=src \
        -Dsonar.java.binaries=. \
        -Dsonar.exclusions=**/*.xml,**/*.txt,**/*.css,test/**
  only:
    - master
